### ISSUE TITLE
focal loss problem

### ISSUE THREAD

**Issue by ljc1231** [junqiangchen/Image-Segmentation-Loss-Functions#2]
focal_loss_sigmodv1 and focal_loss_sigmodv2 which is for 2D segmentation, could i use focal loss plus dice loss like dice_loss+a*focla_loss.
and do you know What value is generally set for a when i use 2D segmentation,thx!

**Comment by junqiangchen** [comment]
you can use any one,but i suggest use focal_loss_sigmodv1 fucntion,you can use mixed loss,the param a is depent on your task,may be have try to decide the value,in general a is 100 or more in 3d segmentation task
